name: Check PR

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g yarn
      - run: yarn
      - run: yarn test
        env:
          CI: true

